services:
  comfyui_backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: comfyui-red-image
    container_name: comfyui-red-container
    ports:
      - "8188:8188"  # Expose the backend API or server
    volumes:
      - ./input:/app/comfyui/input  # Volume for input files
      - ./models:/app/comfyui/models  # Volume for models
      - ./output:/app/comfyui/output  # Volume for output files
      - ./user:/app/comfyui/user  # Volume for user settings, Also this is where your workflows are stored
      #- ./workflows:/app/comfyui/user/default/workflows  # Uncomment if you to make a workflow directory in the comfyui directory

      # Mount the venv directory for persistence (automatically mounted with you run docker-build.sh) #Don't change this

      # Mount the custom nodes directory directly inside /app/comfyui (automatically mounted with you run docker-build.sh)  #Don't change this


    environment:
      - DISPLAY=${DISPLAY}  # Optional, for X11 display forwarding (if you use it)
      - NVIDIA_VISIBLE_DEVICES=all  # Ensure NVIDIA GPU is available to the container
      - NVIDIA_DRIVER_CAPABILITIES=all  # For CUDA support
    runtime: nvidia  # Use the NVIDIA runtime for GPU support 
    restart: "no" #change to "always" if you want to restart the container